# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a76297088cc4f07cee870cff04952b4272605a2661404c90c4bc2b9db8cf616e06e612f712516464dd26d1cf11b2bb63b4643b6850cefdc666111f6cfeb294e4

test:
  secret_key_base: 653670b08de0eceaebf7ab6613132810daba75e95eb6a7361ac3cc007c9dd671459904b79c5235dcb3e182e02299571c0a20296769db28bd9ce0930c3f1ac362

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
